/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Dec 3, 2011, 12:30:48 PM
 */
package gui;

import controllers.SettingsController;
import controllers.CrosswordsController;
import crossword.Settings;
import java.io.IOException;
import javax.swing.UIManager;

/**
 *
 * @author arturhebda
 */
public class MainWindow extends javax.swing.JFrame {

    /** Creates new form MainWindow */
    public MainWindow() {
        settings = new Settings();
        // all controllers share with each other the same instance of settings.
        settingsController = new SettingsController(settings);
        crosswordsController = new CrosswordsController(settings);

        initComponents();
        initMyComponents();
        hideSomeComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        boardTable = new javax.swing.JTable();
        crosswordsBrowserDialog = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        crosswordsList = new javax.swing.JList();
        openCrossword = new javax.swing.JButton();
        settingsDialog = new javax.swing.JInternalFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        databaseFilePath = new javax.swing.JTextField();
        databaseFilePathChange = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        crosswordsDirectoryPath = new javax.swing.JTextField();
        crosswordsDirectoryPathChange = new javax.swing.JButton();
        rows = new javax.swing.JSlider();
        cols = new javax.swing.JSlider();
        saveSettings = new javax.swing.JButton();
        discardSettings = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        PreferencesMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        NewCrosswordMenuItem = new javax.swing.JMenuItem();
        OpenCrosswordMenuItem = new javax.swing.JMenuItem();
        SaveCrosswordMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ResetCrosswordMenuItem = new javax.swing.JMenuItem();
        CheckCrosswordMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        boardTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        boardTable.setCellSelectionEnabled(true);
        boardTable.setTableHeader(null);
        jScrollPane2.setViewportView(boardTable);

        jScrollPane2.setBounds(80, 50, 454, 404);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        crosswordsBrowserDialog.setClosable(true);
        crosswordsBrowserDialog.setTitle("Crosswords Browser");
        crosswordsBrowserDialog.setVisible(true);

        crosswordsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(crosswordsList);

        openCrossword.setText("Open");
        openCrossword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCrosswordActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout crosswordsBrowserDialogLayout = new org.jdesktop.layout.GroupLayout(crosswordsBrowserDialog.getContentPane());
        crosswordsBrowserDialog.getContentPane().setLayout(crosswordsBrowserDialogLayout);
        crosswordsBrowserDialogLayout.setHorizontalGroup(
            crosswordsBrowserDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, crosswordsBrowserDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 174, Short.MAX_VALUE)
                .add(openCrossword)
                .addContainerGap())
        );
        crosswordsBrowserDialogLayout.setVerticalGroup(
            crosswordsBrowserDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(crosswordsBrowserDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(crosswordsBrowserDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(openCrossword))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        crosswordsBrowserDialog.setBounds(90, 210, 430, 217);
        jLayeredPane1.add(crosswordsBrowserDialog, javax.swing.JLayeredPane.DEFAULT_LAYER);

        settingsDialog.setClosable(true);
        settingsDialog.setTitle("Preferences");
        settingsDialog.setVisible(true);
        settingsDialog.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                settingsDialogInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        databaseFilePath.setText("jTextField1");

        databaseFilePathChange.setText("Browse");
        databaseFilePathChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseFilePathChangeActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .add(databaseFilePath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(databaseFilePathChange)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(35, 35, 35)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(databaseFilePath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(databaseFilePathChange))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Dictionary", jPanel2);

        crosswordsDirectoryPath.setText("jTextField2");

        crosswordsDirectoryPathChange.setText("Browse");
        crosswordsDirectoryPathChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crosswordsDirectoryPathChangeActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .add(64, 64, 64)
                .add(crosswordsDirectoryPath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(crosswordsDirectoryPathChange)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .add(rows, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(54, 54, 54))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .add(cols, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(53, 53, 53))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(crosswordsDirectoryPath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(crosswordsDirectoryPathChange))
                .add(18, 18, 18)
                .add(rows, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(cols, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(45, 45, 45))
        );

        jTabbedPane2.addTab("Crosswords", jPanel3);

        saveSettings.setText("Save");
        saveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSettingsActionPerformed(evt);
            }
        });

        discardSettings.setText("Discard Changes");
        discardSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardSettingsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout settingsDialogLayout = new org.jdesktop.layout.GroupLayout(settingsDialog.getContentPane());
        settingsDialog.getContentPane().setLayout(settingsDialogLayout);
        settingsDialogLayout.setHorizontalGroup(
            settingsDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(settingsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 382, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, settingsDialogLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .add(discardSettings)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(saveSettings)
                .addContainerGap())
        );
        settingsDialogLayout.setVerticalGroup(
            settingsDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(settingsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(settingsDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(saveSettings)
                    .add(discardSettings))
                .addContainerGap())
        );

        settingsDialog.setBounds(90, 160, 432, 322);
        jLayeredPane1.add(settingsDialog, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Crossword", jPanel1);

        Menu.setBorder(null);

        jMenu2.setText("jCrosswords");
        jMenu2.setFont(new java.awt.Font("Lucida Grande", 1, 14));

        PreferencesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_COMMA, java.awt.event.InputEvent.CTRL_MASK));
        PreferencesMenuItem.setText("Preferences");
        PreferencesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreferencesMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(PreferencesMenuItem);

        Menu.add(jMenu2);

        jMenu1.setText("File");

        NewCrosswordMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NewCrosswordMenuItem.setText("New");
        jMenu1.add(NewCrosswordMenuItem);

        OpenCrosswordMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenCrosswordMenuItem.setText("Open");
        OpenCrosswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenCrosswordMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(OpenCrosswordMenuItem);

        SaveCrosswordMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveCrosswordMenuItem.setText("Save");
        jMenu1.add(SaveCrosswordMenuItem);
        jMenu1.add(jSeparator1);

        ResetCrosswordMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        ResetCrosswordMenuItem.setText("Reset");
        jMenu1.add(ResetCrosswordMenuItem);

        CheckCrosswordMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CheckCrosswordMenuItem.setText("Check");
        jMenu1.add(CheckCrosswordMenuItem);

        Menu.add(jMenu1);

        setJMenuBar(Menu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 634, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 730, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initMyComponents() {
        databaseFileChooser = new javax.swing.JFileChooser();
        crosswordsFileChooser = new javax.swing.JFileChooser();
        crosswordsFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
    }

    private void hideSomeComponents() {
        settingsDialog.setVisible(false);
        crosswordsBrowserDialog.setVisible(false);
    }

    private void PreferencesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreferencesMenuItemActionPerformed
        // kliknięto Preferences w głównym menu
        settingsDialog.setVisible(true);
    }//GEN-LAST:event_PreferencesMenuItemActionPerformed

    private void discardSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardSettingsActionPerformed
        // discard changes in settings dialog
        settingsDialog.setVisible(false);
        javax.swing.JComponent[] components = { databaseFilePath, crosswordsDirectoryPath, rows, cols };
        settingsController.discardChanges(components);
    }//GEN-LAST:event_discardSettingsActionPerformed

    private void saveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSettingsActionPerformed
        // save in settings dialog
        settingsDialog.setVisible(false);
        javax.swing.JComponent[] components = { databaseFilePath, crosswordsDirectoryPath, rows, cols };
        settingsController.saveChanges(components);
    }//GEN-LAST:event_saveSettingsActionPerformed

    private void settingsDialogInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_settingsDialogInternalFrameClosed
        // closing settings dialog with close button
        javax.swing.JComponent[] components = { databaseFilePath, crosswordsDirectoryPath, rows, cols };
        settingsController.discardChanges(components);
    }//GEN-LAST:event_settingsDialogInternalFrameClosed

    private void databaseFilePathChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseFilePathChangeActionPerformed
        // changing databaseFilePath (optionally after opening JFileChooser)
        javax.swing.JComponent[] components = { databaseFileChooser, databaseFilePath, settingsDialog };
        settingsController.chooseFile(components);
    }//GEN-LAST:event_databaseFilePathChangeActionPerformed

    private void crosswordsDirectoryPathChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crosswordsDirectoryPathChangeActionPerformed
        // changing crosswordsDirectoryPath (optionally after opening JFileChooser)
        javax.swing.JComponent[] components = { crosswordsFileChooser, crosswordsDirectoryPath, settingsDialog };
        settingsController.chooseFile(components);
    }//GEN-LAST:event_crosswordsDirectoryPathChangeActionPerformed

    private void OpenCrosswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenCrosswordMenuItemActionPerformed
        // button 'Open' in Main Menu was clicked
        javax.swing.JComponent[] components = { crosswordsList };
        crosswordsController.prepareCrosswordsList(components);
        crosswordsBrowserDialog.setVisible(true);
    }//GEN-LAST:event_OpenCrosswordMenuItemActionPerformed

    private void openCrosswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCrosswordActionPerformed
        // button 'Open' in Crosswords Browser Dialog
        javax.swing.JComponent[] components = { crosswordsList, boardTable };

        try {
            crosswordsController.showCrossword(components);
            crosswordsBrowserDialog.setVisible(false);
        } catch (IOException e) { System.err.println("ioexception"); }
        catch (ClassNotFoundException e) { System.err.println("classexception"); } // TODO! obsłużyć wyjątki jakoś
    }//GEN-LAST:event_openCrosswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    private Settings settings;
    private SettingsController settingsController;
    private CrosswordsController crosswordsController;
    
    private javax.swing.JFileChooser databaseFileChooser;
    private javax.swing.JFileChooser crosswordsFileChooser;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CheckCrosswordMenuItem;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem NewCrosswordMenuItem;
    private javax.swing.JMenuItem OpenCrosswordMenuItem;
    private javax.swing.JMenuItem PreferencesMenuItem;
    private javax.swing.JMenuItem ResetCrosswordMenuItem;
    private javax.swing.JMenuItem SaveCrosswordMenuItem;
    private javax.swing.JTable boardTable;
    private javax.swing.JSlider cols;
    private javax.swing.JInternalFrame crosswordsBrowserDialog;
    private javax.swing.JTextField crosswordsDirectoryPath;
    private javax.swing.JButton crosswordsDirectoryPathChange;
    private javax.swing.JList crosswordsList;
    private javax.swing.JTextField databaseFilePath;
    private javax.swing.JButton databaseFilePathChange;
    private javax.swing.JButton discardSettings;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton openCrossword;
    private javax.swing.JSlider rows;
    private javax.swing.JButton saveSettings;
    private javax.swing.JInternalFrame settingsDialog;
    // End of variables declaration//GEN-END:variables
}
