/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Dec 3, 2011, 12:30:48 PM
 */
package gui;

import controllers.SettingsController;
import controllers.CrosswordsController;
import crossword.BoardCell;
import crossword.Settings;
import crossword.dictionary.NoRecordsFoundException;
import java.awt.print.PrinterException;
import javax.swing.UIManager;

/**
 *
 * @author arturhebda
 */
public class MainWindow extends javax.swing.JFrame {

    /** Creates new form MainWindow */
    public MainWindow() {
        settings = new Settings();
        // all controllers share with each other the same instance of settings.
        settingsController = new SettingsController(settings);
        crosswordsController = new CrosswordsController(settings);

        initComponents();
        initMyComponents();
        hideSomeComponents();
        preparePrinter();
        populateDefaultSettings();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        strategy = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        crosswordsBrowserDialog = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        crosswordsList = new javax.swing.JList();
        openCrossword = new javax.swing.JButton();
        settingsDialog = new javax.swing.JInternalFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        databaseFilePath = new javax.swing.JTextField();
        databaseFilePathChange = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        crosswordsDirectoryPath = new javax.swing.JTextField();
        crosswordsDirectoryPathChange = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        rows = new javax.swing.JSlider();
        cols = new javax.swing.JSlider();
        jPanel7 = new javax.swing.JPanel();
        simpleStrategy = new javax.swing.JRadioButton();
        realStrategy = new javax.swing.JRadioButton();
        saveSettings = new javax.swing.JButton();
        discardSettings = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        horizontalClues = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        verticalClues = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        boardTable = new javax.swing.JTable();
        errorDialog = new javax.swing.JInternalFrame();
        errorDescription = new javax.swing.JLabel();
        errorDialogCloseButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        errorStackTrace = new javax.swing.JTextArea();
        informalDialog = new javax.swing.JInternalFrame();
        informalMessage = new javax.swing.JLabel();
        informalDialogCloseButton = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        PreferencesMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        NewCrosswordMenuItem = new javax.swing.JMenuItem();
        OpenCrosswordMenuItem = new javax.swing.JMenuItem();
        SaveCrosswordMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ResetCrosswordMenuItem = new javax.swing.JMenuItem();
        CheckCrosswordMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        PrintCrosswordMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crosswordsBrowserDialog.setClosable(true);
        crosswordsBrowserDialog.setTitle("Crosswords Browser");
        crosswordsBrowserDialog.setVisible(true);

        crosswordsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(crosswordsList);

        openCrossword.setText("Open");
        openCrossword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCrosswordActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout crosswordsBrowserDialogLayout = new org.jdesktop.layout.GroupLayout(crosswordsBrowserDialog.getContentPane());
        crosswordsBrowserDialog.getContentPane().setLayout(crosswordsBrowserDialogLayout);
        crosswordsBrowserDialogLayout.setHorizontalGroup(
            crosswordsBrowserDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(crosswordsBrowserDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 229, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 93, Short.MAX_VALUE)
                .add(openCrossword)
                .addContainerGap())
        );
        crosswordsBrowserDialogLayout.setVerticalGroup(
            crosswordsBrowserDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, crosswordsBrowserDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(crosswordsBrowserDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(openCrossword)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addContainerGap())
        );

        crosswordsBrowserDialog.setBounds(50, 137, 460, 280);
        jLayeredPane1.add(crosswordsBrowserDialog, javax.swing.JLayeredPane.DEFAULT_LAYER);

        settingsDialog.setClosable(true);
        settingsDialog.setTitle("Preferences");
        settingsDialog.setVisible(true);
        settingsDialog.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                settingsDialogInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Location of Database File");

        databaseFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseFilePathActionPerformed(evt);
            }
        });

        databaseFilePathChange.setText("Browse");
        databaseFilePathChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseFilePathChangeActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .add(databaseFilePath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 43, Short.MAX_VALUE)
                .add(databaseFilePathChange))
            .add(jPanel8Layout.createSequentialGroup()
                .add(jLabel1)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(databaseFilePath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(databaseFilePathChange))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(45, 45, 45)
                .add(jPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(jPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Dictionary", jPanel2);

        jLabel2.setText("Where to save crosswords?");

        crosswordsDirectoryPathChange.setText("Browse");
        crosswordsDirectoryPathChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crosswordsDirectoryPathChangeActionPerformed(evt);
            }
        });

        jLabel3.setText("How to build them?");

        jLabel4.setText("Columns");

        jLabel5.setText("Rows");

        jLabel6.setText("Strategy");

        rows.setMaximum(30);
        rows.setMinimum(10);
        rows.setMinorTickSpacing(1);
        rows.setValue(20);

        cols.setMaximum(30);
        cols.setMinimum(10);
        cols.setMinorTickSpacing(1);
        cols.setValue(20);

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cols, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rows, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(cols, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rows, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(44, 44, 44))
        );

        strategy.add(simpleStrategy);
        simpleStrategy.setText("Simple Strategy");
        simpleStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleStrategyActionPerformed(evt);
            }
        });

        strategy.add(realStrategy);
        realStrategy.setSelected(true);
        realStrategy.setText("Real Strategy");

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(simpleStrategy)
                    .add(realStrategy))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .add(7, 7, 7)
                .add(simpleStrategy)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(realStrategy)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel3))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel5Layout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(jLabel6)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 116, Short.MAX_VALUE)
                                .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(193, Short.MAX_VALUE)
                        .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 193, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .add(17, 17, 17)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel4)
                        .add(18, 18, 18)
                        .add(jLabel5)))
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(42, 42, 42)
                        .add(jLabel6))
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(crosswordsDirectoryPath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(39, 39, 39)
                        .add(crosswordsDirectoryPathChange))))
            .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(crosswordsDirectoryPath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(crosswordsDirectoryPathChange))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Crosswords", jPanel3);

        saveSettings.setText("Save");
        saveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSettingsActionPerformed(evt);
            }
        });

        discardSettings.setText("Discard Changes");
        discardSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardSettingsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout settingsDialogLayout = new org.jdesktop.layout.GroupLayout(settingsDialog.getContentPane());
        settingsDialog.getContentPane().setLayout(settingsDialogLayout);
        settingsDialogLayout.setHorizontalGroup(
            settingsDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(settingsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(settingsDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, settingsDialogLayout.createSequentialGroup()
                        .add(discardSettings)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(saveSettings))
                    .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap())
        );
        settingsDialogLayout.setVerticalGroup(
            settingsDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, settingsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(settingsDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(saveSettings)
                    .add(discardSettings))
                .addContainerGap())
        );

        settingsDialog.setBounds(20, 30, 520, 520);
        jLayeredPane1.add(settingsDialog, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane3.setEnabled(false);

        horizontalClues.setColumns(2);
        horizontalClues.setEditable(false);
        horizontalClues.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        horizontalClues.setRows(5);
        jScrollPane3.setViewportView(horizontalClues);

        jTabbedPane3.addTab("Horizontal", jScrollPane3);

        jScrollPane4.setEnabled(false);

        verticalClues.setColumns(2);
        verticalClues.setEditable(false);
        verticalClues.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        verticalClues.setRows(5);
        jScrollPane4.setViewportView(verticalClues);

        jTabbedPane3.addTab("Vertical", jScrollPane4);

        jTabbedPane3.setBounds(0, 390, 560, 230);
        jLayeredPane1.add(jTabbedPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        boardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        boardTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        boardTable.setCellSelectionEnabled(true);
        boardTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        boardTable.setTableHeader(null);
        jScrollPane2.setViewportView(boardTable);

        jScrollPane2.setBounds(10, 10, 540, 370);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        errorDialog.setClosable(true);
        errorDialog.setTitle("Dang!");
        errorDialog.setVisible(true);
        errorDialog.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                errorDialogInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        errorDescription.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        errorDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        errorDialogCloseButton.setText("Ok");
        errorDialogCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorDialogCloseButtonActionPerformed(evt);
            }
        });

        errorStackTrace.setColumns(20);
        errorStackTrace.setEditable(false);
        errorStackTrace.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        errorStackTrace.setRows(5);
        jScrollPane5.setViewportView(errorStackTrace);

        org.jdesktop.layout.GroupLayout errorDialogLayout = new org.jdesktop.layout.GroupLayout(errorDialog.getContentPane());
        errorDialog.getContentPane().setLayout(errorDialogLayout);
        errorDialogLayout.setHorizontalGroup(
            errorDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, errorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(errorDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, errorDescription, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .add(errorDialogCloseButton))
                .addContainerGap())
        );
        errorDialogLayout.setVerticalGroup(
            errorDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(errorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(errorDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(errorDialogCloseButton)
                .addContainerGap())
        );

        errorDialog.setBounds(24, 30, 510, 530);
        jLayeredPane1.add(errorDialog, javax.swing.JLayeredPane.DEFAULT_LAYER);

        informalDialog.setClosable(true);
        informalDialog.setVisible(true);

        informalMessage.setText("jLabel7");
        informalMessage.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        informalDialogCloseButton.setText("Ok");
        informalDialogCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informalDialogCloseButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout informalDialogLayout = new org.jdesktop.layout.GroupLayout(informalDialog.getContentPane());
        informalDialog.getContentPane().setLayout(informalDialogLayout);
        informalDialogLayout.setHorizontalGroup(
            informalDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(informalDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(informalDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, informalDialogCloseButton)
                    .add(informalMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addContainerGap())
        );
        informalDialogLayout.setVerticalGroup(
            informalDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, informalDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(informalMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(informalDialogCloseButton)
                .addContainerGap())
        );

        informalDialog.setBounds(140, 210, 280, 160);
        jLayeredPane1.add(informalDialog, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Crossword", jPanel1);

        Menu.setBorder(null);

        jMenu2.setText("jCrosswords");
        jMenu2.setFont(new java.awt.Font("Lucida Grande", 1, 14));

        PreferencesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_COMMA, java.awt.event.InputEvent.CTRL_MASK));
        PreferencesMenuItem.setText("Preferences");
        PreferencesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreferencesMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(PreferencesMenuItem);

        Menu.add(jMenu2);

        jMenu1.setText("File");

        NewCrosswordMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NewCrosswordMenuItem.setText("New");
        NewCrosswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCrosswordMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(NewCrosswordMenuItem);

        OpenCrosswordMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenCrosswordMenuItem.setText("Open");
        OpenCrosswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenCrosswordMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(OpenCrosswordMenuItem);

        SaveCrosswordMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveCrosswordMenuItem.setText("Save");
        SaveCrosswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveCrosswordMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(SaveCrosswordMenuItem);
        jMenu1.add(jSeparator1);

        ResetCrosswordMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        ResetCrosswordMenuItem.setText("Reset");
        ResetCrosswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetCrosswordMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(ResetCrosswordMenuItem);

        CheckCrosswordMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CheckCrosswordMenuItem.setText("Check");
        CheckCrosswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckCrosswordMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(CheckCrosswordMenuItem);
        jMenu1.add(jSeparator2);

        PrintCrosswordMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        PrintCrosswordMenuItem.setText("Print");
        PrintCrosswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintCrosswordMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(PrintCrosswordMenuItem);

        Menu.add(jMenu1);

        setJMenuBar(Menu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 666, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initMyComponents() {
        databaseFileChooser = new javax.swing.JFileChooser();
        crosswordsFileChooser = new javax.swing.JFileChooser();
        crosswordsFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        boardTable.setDefaultRenderer(BoardCell.class, new MyTableCellRenderer());
        boardTable.setDefaultEditor(BoardCell.class, new MyTableCellEditor());
    }

    private void hideSomeComponents() {
        // settingsDialog.setVisible(false);
        errorDialog.setVisible(false);
        crosswordsBrowserDialog.setVisible(false);
        informalDialog.setVisible(false);
    }

    private void preparePrinter() {
        javax.swing.JComponent[] printableComponents = { boardTable, horizontalClues, verticalClues };
        String[] headers = { "jCrosswords", "Horizontal", "Vertical" };

        printer = new Printer(printableComponents, headers);
    }

    private void populateDefaultSettings() {
        cols.setMinimum(Settings.MIN_COLS);
        cols.setMaximum(Settings.MAX_COLS);
        cols.setValue(Settings.DEFAULT_COLS);

        rows.setMinimum(Settings.MIN_ROWS);
        rows.setMaximum(Settings.MAX_ROWS);
        rows.setValue(Settings.DEFAULT_ROWS);

        crosswordsDirectoryPath.setText(settings.getCrosswordsDirectoryPath());
        databaseFilePath.setText(settings.getDatabaseFilePath());
    }

    private void PreferencesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreferencesMenuItemActionPerformed
        // kliknięto Preferences w głównym menu
        settingsDialog.setVisible(true);
    }//GEN-LAST:event_PreferencesMenuItemActionPerformed

    private void discardSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardSettingsActionPerformed
        // discard changes in settings dialog
        settingsDialog.setVisible(false);
        javax.swing.JComponent[] components = { databaseFilePath, crosswordsDirectoryPath, rows, cols, simpleStrategy, realStrategy };
        settingsController.discardChanges(components);
    }//GEN-LAST:event_discardSettingsActionPerformed

    private void saveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSettingsActionPerformed
        // save in settings dialog
        settingsDialog.setVisible(false);
        javax.swing.JComponent[] components = { databaseFilePath, crosswordsDirectoryPath, rows, cols, simpleStrategy, realStrategy };
        settingsController.saveChanges(components);
    }//GEN-LAST:event_saveSettingsActionPerformed

    private void settingsDialogInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_settingsDialogInternalFrameClosed
        // closing settings dialog with close button
        javax.swing.JComponent[] components = { databaseFilePath, crosswordsDirectoryPath, rows, cols, simpleStrategy, realStrategy };
        settingsController.discardChanges(components);
    }//GEN-LAST:event_settingsDialogInternalFrameClosed

    private void databaseFilePathChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseFilePathChangeActionPerformed
        // changing databaseFilePath (optionally after opening JFileChooser)
        javax.swing.JComponent[] components = { databaseFileChooser, databaseFilePath, settingsDialog };
        settingsController.chooseFile(components);
    }//GEN-LAST:event_databaseFilePathChangeActionPerformed

    private void crosswordsDirectoryPathChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crosswordsDirectoryPathChangeActionPerformed
        // changing crosswordsDirectoryPath (optionally after opening JFileChooser)
        javax.swing.JComponent[] components = { crosswordsFileChooser, crosswordsDirectoryPath, settingsDialog };
        settingsController.chooseFile(components);
    }//GEN-LAST:event_crosswordsDirectoryPathChangeActionPerformed

    private void OpenCrosswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenCrosswordMenuItemActionPerformed
        // button 'Open' in Main Menu was clicked
        javax.swing.JComponent[] components = { crosswordsList };
        crosswordsController.prepareCrosswordsList(components);
        crosswordsBrowserDialog.setVisible(true);
    }//GEN-LAST:event_OpenCrosswordMenuItemActionPerformed

    private void openCrosswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCrosswordActionPerformed
        // button 'Open' in Crosswords Browser Dialog
        javax.swing.JComponent[] components = { crosswordsList, boardTable, horizontalClues, verticalClues };

        try {
            crosswordsController.showCrossword(components);
            crosswordsBrowserDialog.setVisible(false);
        } catch (Exception e) { openErrorDialog(e); }
    }//GEN-LAST:event_openCrosswordActionPerformed

    private void NewCrosswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCrosswordMenuItemActionPerformed
        // new in main menu
        javax.swing.JComponent[] components = { boardTable, horizontalClues, verticalClues };

        try {
            crosswordsController.generateAndShowCrossword(components);
        } catch (Exception e) { openErrorDialog(e); }
    }//GEN-LAST:event_NewCrosswordMenuItemActionPerformed

    private void simpleStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleStrategyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpleStrategyActionPerformed

    private void databaseFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_databaseFilePathActionPerformed

    private void ResetCrosswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetCrosswordMenuItemActionPerformed
        // clear crossword's board
        javax.swing.JComponent[] components = { boardTable };
        crosswordsController.resetCrossword(components);
    }//GEN-LAST:event_ResetCrosswordMenuItemActionPerformed

    private void SaveCrosswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveCrosswordMenuItemActionPerformed
        // save crossword
        try {
            crosswordsController.saveCrossword();
            openInformalDialog("Saved successfully!");
        } catch (Exception e) { openErrorDialog(e); }
    }//GEN-LAST:event_SaveCrosswordMenuItemActionPerformed

    private void errorDialogCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorDialogCloseButtonActionPerformed
        // close error dialog
        errorDialog.setVisible(false);
    }//GEN-LAST:event_errorDialogCloseButtonActionPerformed

    private void errorDialogInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_errorDialogInternalFrameClosed
        // closing error dialog
        errorDialog.setVisible(false);
    }//GEN-LAST:event_errorDialogInternalFrameClosed

    private void PrintCrosswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintCrosswordMenuItemActionPerformed
        try {
            // print in main menu
            printer.print();
        } catch (PrinterException e) { openErrorDialog(e); }
    }//GEN-LAST:event_PrintCrosswordMenuItemActionPerformed

    private void informalDialogCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informalDialogCloseButtonActionPerformed
        // closing informal dialog
        informalDialog.setVisible(false);
    }//GEN-LAST:event_informalDialogCloseButtonActionPerformed

    private void CheckCrosswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckCrosswordMenuItemActionPerformed
        // check in main menu
        javax.swing.JComponent[] components = { boardTable };
        crosswordsController.checkCrossword(components);
    }//GEN-LAST:event_CheckCrosswordMenuItemActionPerformed

    private void openErrorDialog(Exception ex) {
        String errorText = "<html><b>Unfortunately something went wrong.</b><br><br>";

        if (ex.getClass().getSimpleName().equals("PrinterException"))
            errorText += "Please check your printer or destination file's location.";
        else
            errorText += "Please check directory for crosswords and database file's path and format.";

        errorText += "<br><br>Error type: <b>" + ex.getClass().getName() + "</b></html>";
        errorDescription.setText(errorText);

        String stackTrace = "";

        for (StackTraceElement stackFrame : ex.getStackTrace())
            stackTrace += stackFrame.toString() + "\n";

        errorStackTrace.setText(stackTrace);
        errorDialog.setVisible(true);
    }

    private void openInformalDialog(String message) {
        informalMessage.setText(message);
        informalDialog.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    private Printer printer;
    private Settings settings;
    private SettingsController settingsController;
    private CrosswordsController crosswordsController;
    
    private javax.swing.JFileChooser databaseFileChooser;
    private javax.swing.JFileChooser crosswordsFileChooser;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CheckCrosswordMenuItem;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem NewCrosswordMenuItem;
    private javax.swing.JMenuItem OpenCrosswordMenuItem;
    private javax.swing.JMenuItem PreferencesMenuItem;
    private javax.swing.JMenuItem PrintCrosswordMenuItem;
    private javax.swing.JMenuItem ResetCrosswordMenuItem;
    private javax.swing.JMenuItem SaveCrosswordMenuItem;
    private javax.swing.JTable boardTable;
    private javax.swing.JSlider cols;
    private javax.swing.JInternalFrame crosswordsBrowserDialog;
    private javax.swing.JTextField crosswordsDirectoryPath;
    private javax.swing.JButton crosswordsDirectoryPathChange;
    private javax.swing.JList crosswordsList;
    private javax.swing.JTextField databaseFilePath;
    private javax.swing.JButton databaseFilePathChange;
    private javax.swing.JButton discardSettings;
    private javax.swing.JLabel errorDescription;
    private javax.swing.JInternalFrame errorDialog;
    private javax.swing.JButton errorDialogCloseButton;
    private javax.swing.JTextArea errorStackTrace;
    private javax.swing.JTextArea horizontalClues;
    private javax.swing.JInternalFrame informalDialog;
    private javax.swing.JButton informalDialogCloseButton;
    private javax.swing.JLabel informalMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton openCrossword;
    private javax.swing.JRadioButton realStrategy;
    private javax.swing.JSlider rows;
    private javax.swing.JButton saveSettings;
    private javax.swing.JInternalFrame settingsDialog;
    private javax.swing.JRadioButton simpleStrategy;
    private javax.swing.ButtonGroup strategy;
    private javax.swing.JTextArea verticalClues;
    // End of variables declaration//GEN-END:variables
}
